permissions:
  contents: write   # Omogućava GitHub Actions-u pisanje u repozitorij (commit, push)
  pull-requests: write  # Omogućava GitHub Actions-u upravljanje pull zahtjevima
  issues: write  # Omogućava GitHub Actions-u upravljanje problemima
  discussions: write  # Omogućava GitHub Actions-u upravljanje diskusijama

# Ostatak workflow-a
name: Auto Build Sonarr

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'  # svakodnevno u 05:00 UTC

env:
  PLATFORM: linux/arm/v7
  IMAGE_NAME: mojrapid/sonarr
  ARCH_TAG: arm32v7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.10.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if image already exists
        id: check_image
        run: |
          image_tag="${{ env.IMAGE_NAME }}:${{ env.ARCH_TAG }}-${{ env.SONARR_VERSION }}"
          image_exists=$(docker manifest inspect $image_tag || echo "not found")
          if [[ $image_exists == *"not found"* ]]; then
            echo "Image not found. Proceeding with build."
            echo "image_exists=false" >> $GITHUB_ENV
          else
            echo "Image found. Skipping build."
            echo "image_exists=true" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker image
        if: env.image_exists == 'false'
        uses: docker/build-push-action@v5
        with:
          context: ./  # Koristi root direktorij za build
          file: ./Dockerfile  # Putanja do Dockerfile-a u repozitoriju
          push: true
          platforms: ${{ env.PLATFORM }}
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            SONARR_VERSION=${{ env.SONARR_VERSION }}
            VERSION=${{ env.SONARR_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.ARCH_TAG }}-${{ env.SONARR_VERSION }}
            ${{ env.IMAGE_NAME }}:${{ env.ARCH_TAG }}-latest

      - name: Send Discord notification on success
        if: env.image_exists == 'false'
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "New Sonarr image version '${{ env.SONARR_VERSION }}' has been built and pushed to Docker Hub."}' ${{ secrets.DISCORD_WEBHOOK }}

      - name: Send Discord notification on failure
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "Build failed for Sonarr image version '${{ env.SONARR_VERSION }}'. Please check the build logs."}' ${{ secrets.DISCORD_WEBHOOK }}
